pipeline:

  build:
    image: node
    commands:
      - npm install

  lint:
    image: node
    commands:
      - npm run lint

  release:
    image: plugins/docker
    dockerfile: docker/Dockerfile
    repo: nexusstats/nexus-bot
    no_cache: true
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: [ push ]
