version: '3.4'


services:
  nexus_bot:
    build: .
    image: nexusstats/nexus-bot-rework:latest
    secrets:
      - nexus-bot-discord-token
      - nexus-cubic-key
      - nexus-cubic-secret
      - mongo-admin-pwd
    # environment:
    #  - DOCKER=true
  mongo:
    image: mongo


secrets:
  nexus-bot-discord-token:
    external: true
  nexus-cubic-key:
    external: true
  nexus-cubic-secret:
    external: true
  mongo-admin-pwd:
    external: true
