version: '3.4'


services:
  nexus_bot:
    image: nexusstats/nexus-bot-rework:latest
    secrets:
      - nexus-bot-discord-token
      - nexus-cubic-key
      - nexus-cubic-secret
    depends_on:
      - mongo
    environment:
      - DOCKER=true

secrets:
  nexus-bot-discord-token:
    external: true
  nexus-cubic-key:
    external: true
  nexus-cubic-secret:
    external: true
