version: '3.4'


services:
  nexus_bot:
    image: nexusstats/nexus-bot-rework:latest
    secrets:
      - nexus-bot-discord-token
      - nexus-cubic-key
      - nexus-cubic-secret
    depends_on:
      - mongo
    command: ["/bin/sh", "/app/nexus-bot/wait-for.sh", "mongo:27017", "--", "node", "/app/nexus-bot"]
    networks:
      - bot_network
    environment:
      - NODE_ENV=production
    logging:
      options:
        max-file: "5"
        max-size: "10m"
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    networks:
      - bot_network
    ports:
      - "27017:27017"
    logging:
      options:
        max-file: "5"
        max-size: "10m"


networks:
  bot_network:
    driver: overlay


secrets:
  nexus-bot-discord-token:
    external: true
  nexus-cubic-key:
    external: true
  nexus-cubic-secret:
    external: true
