version: '3.4'


services:
  nexus_bot:
    image: nexusstats/nexus-bot-rework:latest
    secrets:
      - nexus-bot-discord-token
      - nexus-cubic-key
      - nexus-cubic-secret
    depends_on:
      - mongo
    networks:
      - bot_network
    environment:
      - NODE_ENV=production
  mongo:
    image: mongo
    networks:
      - bot_network
    ports:
      - "27017:27017"


networks:
  bot_network:
    driver: overlay


secrets:
  nexus-bot-discord-token:
    external: true
  nexus-cubic-key:
    external: true
  nexus-cubic-secret:
    external: true
